services:
  
  mongodb:
    image: mongo:7.0
    environment:
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - food-delivery-swarm-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password123
      ME_CONFIG_MONGODB_ADMINUSERNAME: ""
      ME_CONFIG_MONGODB_ADMINPASSWORD: ""
    networks:
      - food-delivery-swarm-network

  backend:
    image: food-delivery-backend
    environment:
      JWT_SECRET: ${JWT_SECRET:-mySecretKey123!@#}
      SALT: ${SALT:-10}
      MONGO_URL: mongodb://mongodb:27017/${MONGO_DATABASE:-mydatabase}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:-your_stripe_key_here}
      PORT: ${BACKEND_PORT:-4000}
    ports:
      - "4000:4000"
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - food-delivery-swarm-network
    deploy:
      replicas: 2

  frontend:
    image: food-delivery-frontend
    ports:
      - "3000:80"
    networks:
      - food-delivery-swarm-network
    deploy:
      replicas: 2

  admin:
    image: food-delivery-admin
    ports:
      - "3001:80"
    networks:
      - food-delivery-swarm-network
    deploy:
      replicas: 1

networks:
  food-delivery-swarm-network:
    driver: overlay
    attachable: true

volumes:
  mongodb_data:
    name: food-delivery-mongodb-data