services:
  
  mongodb:
    image: mongo:7.0
    container_name: food-delivery-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - food-delivery-network

  mongo-express:
    image: mongo-express:latest
    container_name: food-delivery-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password123
      ME_CONFIG_MONGODB_ADMINUSERNAME: ""
      ME_CONFIG_MONGODB_ADMINPASSWORD: ""
    depends_on:
      - mongodb
    networks:
      - food-delivery-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: food-delivery-backend
    restart: unless-stopped
    environment:
      JWT_SECRET: ${JWT_SECRET:-mySecretKey123!@#}
      SALT: ${SALT:-10}
      MONGO_URL: mongodb://mongodb:27017/${MONGO_DATABASE:-mydatabase}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY:-your_stripe_key_here}
      PORT: ${BACKEND_PORT:-4000}
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - food-delivery-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=http://localhost:4000
    container_name: food-delivery-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - food-delivery-network

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=http://localhost:4000
    container_name: food-delivery-admin
    restart: unless-stopped
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - food-delivery-network

networks:
  food-delivery-network:
    driver: bridge
    name: food-delivery-network

volumes:
  mongodb_data:
    name: food-delivery-mongodb-data