#!/bin/bash

# Quick Guide to Using Monitoring Stack

echo "📊 ======================================================"
echo "   MONITORING STACK - QUICK START GUIDE"
echo "========================================================"
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}🎯 PROMETHEUS (http://localhost:9090)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "What to do:"
echo "  1. Check Targets: http://localhost:9090/targets"
echo "     → See which services are being monitored"
echo "     → Verify all targets are 'UP'"
echo ""
echo "  2. Run Queries: http://localhost:9090/graph"
echo "     Try these queries:"
echo "     • CPU Usage: rate(process_cpu_seconds_total[5m])"
echo "     • Memory: node_memory_MemAvailable_bytes"
echo "     • Disk Space: node_filesystem_avail_bytes"
echo "     • Container CPU: rate(container_cpu_usage_seconds_total[5m])"
echo ""
echo "  3. View Alerts: http://localhost:9090/alerts"
echo "     → See active and pending alerts"
echo ""

echo -e "${BLUE}📈 GRAFANA (http://localhost:3002)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Login: admin / admin (change password on first login)"
echo ""
echo "What to do:"
echo "  1. Import Pre-built Dashboards:"
echo "     → Click '+' → Import"
echo "     → Enter these Dashboard IDs:"
echo "       • 1860 - Node Exporter Full"
echo "       • 193  - Docker Container & Host Metrics"
echo "       • 3662 - Prometheus 2.0 Overview"
echo "       • 893  - Docker & System Monitoring"
echo ""
echo "  2. Create Custom Dashboard:"
echo "     → Click '+' → Create Dashboard"
echo "     → Add Panel → Select metric"
echo "     → Choose visualization (Graph, Gauge, etc.)"
echo ""
echo "  3. Set Up Alerts (optional):"
echo "     → Edit Panel → Alert tab"
echo "     → Define alert conditions"
echo ""

echo -e "${BLUE}🔔 ALERTMANAGER (http://localhost:9093)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "What to do:"
echo "  1. View Active Alerts"
echo "     → See current firing alerts"
echo ""
echo "  2. Silence Alerts"
echo "     → Click 'Silence' to temporarily mute alerts"
echo "     → Set duration and reason"
echo ""
echo "  3. Configure Notifications (later):"
echo "     → Edit: monitoring/alertmanager.yml"
echo "     → Add email/Slack receivers"
echo "     → Restart: docker restart alertmanager"
echo ""

echo -e "${BLUE}📊 NODE EXPORTER (http://localhost:9100/metrics)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "What to do:"
echo "  • View raw metrics (system stats)"
echo "  • Used automatically by Prometheus"
echo ""

echo -e "${BLUE}🐳 cADVISOR (http://localhost:8081)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "What to do:"
echo "  1. View Container Stats"
echo "     → Click on containers to see details"
echo "     → CPU, Memory, Network graphs"
echo ""
echo "  2. Docker Host Info"
echo "     → System resources"
echo "     → Running containers"
echo ""

echo ""
echo -e "${YELLOW}🚀 RECOMMENDED WORKFLOW:${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step 1: Check Prometheus Targets (2 min)"
echo "  open http://localhost:9090/targets"
echo "  → All should be green/UP"
echo ""
echo "Step 2: Import Grafana Dashboards (5 min)"
echo "  open http://localhost:3002"
echo "  → Import dashboard ID: 1860"
echo "  → Select Prometheus datasource"
echo "  → View beautiful visualizations!"
echo ""
echo "Step 3: Explore Your Metrics (10 min)"
echo "  → In Grafana, explore different panels"
echo "  → See CPU, Memory, Disk usage in real-time"
echo "  → Check container resource consumption"
echo ""
echo "Step 4: Test an Alert (5 min)"
echo "  → Run: stress --cpu 8 --timeout 120"
echo "  → Check Prometheus alerts: http://localhost:9090/alerts"
echo "  → See alert in Alertmanager: http://localhost:9093"
echo ""

echo ""
echo -e "${GREEN}✅ QUICK COMMANDS:${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Open Grafana:       open http://localhost:3002"
echo "  Open Prometheus:    open http://localhost:9090"
echo "  View logs:          docker-compose -f docker-compose.monitoring.yml logs -f"
echo "  Restart services:   docker-compose -f docker-compose.monitoring.yml restart"
echo "  Stop monitoring:    ./stop-monitoring.sh"
echo ""

echo -e "${YELLOW}📚 Next Steps:${NC}"
echo "  1. Import Grafana dashboards (start with ID: 1860)"
echo "  2. Configure email alerts in alertmanager.yml"
echo "  3. Add application metrics to backend (see TASK_11_MONITORING_COMPLETE.md)"
echo ""
