apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: food-delivery-backend:latest
        imagePullPolicy: Never  # Pour les images locales
        ports:
        - containerPort: 4000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: JWT_SECRET
          value: "mySecretKey123!@#"
        - name: SALT
          value: "10"
        - name: MONGO_URL
          value: "mongodb://mongodb-service:27017/mydatabase"
        - name: STRIPE_SECRET_KEY
          value: "your_stripe_key_here"
        - name: PORT
          value: "4000"
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 4000
    targetPort: 4000
  type: ClusterIP