FROM jenkins/jenkins:lts

USER root

# Installer Docker CLI
RUN apt-get update && \
    apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get update && \
    apt-get install -y docker-ce-cli && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Ajouter l'utilisateur jenkins au groupe docker
RUN groupadd -f docker && usermod -aG docker jenkins

USER jenkins

# Installer les plugins Jenkins recommandés
RUN jenkins-plugin-cli --plugins \
    docker-workflow \
    docker-plugin \
    git \
    workflow-aggregator \
    kubernetes \
    kubernetes-cli
